# Generated by Django 5.0.3 on 2024-04-04 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='contact',
            name='show',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 4, 22, 42, 29, 505217, tzinfo=datetime.timezone.utc)),
        ),
    ]
