# Generated by Django 5.0.3 on 2024-04-04 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_category_alter_contact_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 4, 23, 43, 52, 519230, tzinfo=datetime.timezone.utc)),
        ),
    ]
